// ReSharper disable once CppMissingIncludeGuard
VULKAN_FUNCTION(DestroyInstance, void, Instance, const VkAllocationCallbacks*)
VULKAN_FUNCTION(EnumeratePhysicalDevices, VkResult, Instance, uint32_t*, VkPhysicalDevice*)
VULKAN_FUNCTION(GetFeatures, void, PhysicalDevice, VkPhysicalDeviceFeatures*)
VULKAN_FUNCTION(GetFormatProperties, void, PhysicalDevice, VkFormat, VkFormatProperties*)
VULKAN_FUNCTION(GetImageFormatProperties, VkResult, PhysicalDevice, VkFormat, VkImageType, VkImageTiling, VkImageUsageFlags, VkImageCreateFlags, VkImageFormatProperties*)
VULKAN_FUNCTION(GetProperties, void, PhysicalDevice, VkPhysicalDeviceProperties*)
VULKAN_FUNCTION(GetQueueFamilyProperties, void, PhysicalDevice, uint32_t*, VkQueueFamilyProperties*)
VULKAN_FUNCTION(GetMemoryProperties, void, PhysicalDevice, VkPhysicalDeviceMemoryProperties*)
VULKAN_FUNCTION(GetProcAddress, PFN_vkVoidFunction, Instance, const char*)
VULKAN_FUNCTION(GetProcAddress, PFN_vkVoidFunction, Device, const char*)
VULKAN_FUNCTION(CreateDevice, VkResult, PhysicalDevice, const VkDeviceCreateInfo*, const VkAllocationCallbacks*, VkDevice*)
VULKAN_FUNCTION(DestroyDevice, void, Device, const VkAllocationCallbacks*)
VULKAN_FUNCTION(EnumerateDeviceExtensionProperties, VkResult, PhysicalDevice, const char*, uint32_t*, VkExtensionProperties*)
VULKAN_FUNCTION(EnumerateDeviceLayerProperties, VkResult, PhysicalDevice, uint32_t*, VkLayerProperties*)
VULKAN_FUNCTION(GetDeviceQueue, void, Device, uint32_t, uint32_t, VkQueue*)
VULKAN_FUNCTION(Submit, VkResult, Queue, uint32_t, const VkSubmitInfo*, VkFence)
VULKAN_FUNCTION(WaitIdle, VkResult, Queue)
VULKAN_FUNCTION(WaitIdle, VkResult, Device)
VULKAN_FUNCTION(AllocateMemory, VkResult, Device, const VkMemoryAllocateInfo*, const VkAllocationCallbacks*, VkDeviceMemory*)
VULKAN_FUNCTION(FreeMemory, void, Device, VkDeviceMemory, const VkAllocationCallbacks*)
VULKAN_FUNCTION(MapMemory, VkResult, Device, VkDeviceMemory, VkDeviceSize, VkDeviceSize, VkMemoryMapFlags, void**)
VULKAN_FUNCTION(UnmapMemory, void, Device, VkDeviceMemory)
VULKAN_FUNCTION(FlushMappedMemoryRanges, VkResult, Device, uint32_t, const VkMappedMemoryRange*)
VULKAN_FUNCTION(InvalidateMappedMemoryRanges, VkResult, Device, uint32_t, const VkMappedMemoryRange*)
VULKAN_FUNCTION(GetDeviceMemoryCommitment, void, Device, VkDeviceMemory, VkDeviceSize*)
VULKAN_FUNCTION(BindBufferMemory, VkResult, Device, VkBuffer, VkDeviceMemory, VkDeviceSize)
VULKAN_FUNCTION(BindImageMemory, VkResult, Device, VkImage, VkDeviceMemory, VkDeviceSize)
VULKAN_FUNCTION(GetBufferMemoryRequirements, void, Device, VkBuffer, VkMemoryRequirements*)
VULKAN_FUNCTION(GetImageMemoryRequirements, void, Device, VkImage, VkMemoryRequirements*)
VULKAN_FUNCTION(GetImageSparseMemoryRequirements, void, Device, VkImage, uint32_t*, VkSparseImageMemoryRequirements*)
VULKAN_FUNCTION(GetSparseImageFormatProperties, void, PhysicalDevice, VkFormat, VkImageType, VkSampleCountFlagBits, VkImageUsageFlags, VkImageTiling, uint32_t*, VkSparseImageFormatProperties*)
VULKAN_FUNCTION(BindSparse, VkResult, Queue, uint32_t, const VkBindSparseInfo*, VkFence)
VULKAN_FUNCTION(CreateFence, VkResult, Device, const VkFenceCreateInfo*, const VkAllocationCallbacks*, VkFence*)
VULKAN_FUNCTION(DestroyFence, void, Device, VkFence, const VkAllocationCallbacks*)
VULKAN_FUNCTION(ResetFences, VkResult, Device, uint32_t, const VkFence*)
VULKAN_FUNCTION(GetFenceStatus, VkResult, Device, VkFence)
VULKAN_FUNCTION(WaitForFences, VkResult, Device, uint32_t, const VkFence*, VkBool32, uint64_t)
VULKAN_FUNCTION(CreateSemaphore, VkResult, Device, const VkSemaphoreCreateInfo*, const VkAllocationCallbacks*, VkSemaphore*)
VULKAN_FUNCTION(DestroySemaphore, void, Device, VkSemaphore, const VkAllocationCallbacks*)
VULKAN_FUNCTION(CreateEvent, VkResult, Device, const VkEventCreateInfo*, const VkAllocationCallbacks*, VkEvent*)
VULKAN_FUNCTION(DestroyEvent, void, Device, VkEvent, const VkAllocationCallbacks*)
VULKAN_FUNCTION(GetEventStatus, VkResult, Device, VkEvent)
VULKAN_FUNCTION(SetEvent, VkResult, Device, VkEvent)
VULKAN_FUNCTION(ResetEvent, VkResult, Device, VkEvent)
VULKAN_FUNCTION(CreateQueryPool, VkResult, Device, const VkQueryPoolCreateInfo*, const VkAllocationCallbacks*, VkQueryPool*)
VULKAN_FUNCTION(DestroyQueryPool, void, Device, VkQueryPool, const VkAllocationCallbacks*)
VULKAN_FUNCTION(GetQueryPoolResults, VkResult, Device, VkQueryPool, uint32_t, uint32_t, size_t, void*, VkDeviceSize, VkQueryResultFlags)
VULKAN_FUNCTION(CreateBuffer, VkResult, Device, const VkBufferCreateInfo*, const VkAllocationCallbacks*, VkBuffer*)
VULKAN_FUNCTION(DestroyBuffer, void, Device, VkBuffer, const VkAllocationCallbacks*)
VULKAN_FUNCTION(CreateBufferView, VkResult, Device, const VkBufferViewCreateInfo*, const VkAllocationCallbacks*, VkBufferView*)
VULKAN_FUNCTION(DestroyBufferView, void, Device, VkBufferView, const VkAllocationCallbacks*)
VULKAN_FUNCTION(CreateImage, VkResult, Device, const VkImageCreateInfo*, const VkAllocationCallbacks*, VkImage*)
VULKAN_FUNCTION(DestroyImage, void, Device, VkImage, const VkAllocationCallbacks*)
VULKAN_FUNCTION(GetImageSubresourceLayout, void, Device, VkImage, const VkImageSubresource*, VkSubresourceLayout*)
VULKAN_FUNCTION(CreateImageView, VkResult, Device, const VkImageViewCreateInfo*, const VkAllocationCallbacks*, VkImageView*)
VULKAN_FUNCTION(DestroyImageView, void, Device, VkImageView, const VkAllocationCallbacks*)
VULKAN_FUNCTION(CreateShaderModule, VkResult, Device, const VkShaderModuleCreateInfo*, const VkAllocationCallbacks*, VkShaderModule*)
VULKAN_FUNCTION(DestroyShaderModule, void, Device, VkShaderModule, const VkAllocationCallbacks*)
VULKAN_FUNCTION(CreatePipelineCache, VkResult, Device, const VkPipelineCacheCreateInfo*, const VkAllocationCallbacks*, VkPipelineCache*)
VULKAN_FUNCTION(DestroyPipelineCache, void, Device, VkPipelineCache, const VkAllocationCallbacks*)
VULKAN_FUNCTION(GetPipelineCacheData, VkResult, Device, VkPipelineCache, size_t*, void*)
VULKAN_FUNCTION(MergePipelineCaches, VkResult, Device, VkPipelineCache, uint32_t, const VkPipelineCache*)
VULKAN_FUNCTION(CreateGraphicsPipelines, VkResult, Device, VkPipelineCache, uint32_t, const VkGraphicsPipelineCreateInfo*, const VkAllocationCallbacks*, VkPipeline*)
VULKAN_FUNCTION(CreateComputePipelines, VkResult, Device, VkPipelineCache, uint32_t, const VkComputePipelineCreateInfo*, const VkAllocationCallbacks*, VkPipeline*)
VULKAN_FUNCTION(DestroyPipeline, void, Device, VkPipeline, const VkAllocationCallbacks*)
VULKAN_FUNCTION(CreatePipelineLayout, VkResult, Device, const VkPipelineLayoutCreateInfo*, const VkAllocationCallbacks*, VkPipelineLayout*)
VULKAN_FUNCTION(DestroyPipelineLayout, void, Device, VkPipelineLayout, const VkAllocationCallbacks*)
VULKAN_FUNCTION(CreateSampler, VkResult, Device, const VkSamplerCreateInfo*, const VkAllocationCallbacks*, VkSampler*)
VULKAN_FUNCTION(DestroySampler, void, Device, VkSampler, const VkAllocationCallbacks*)
VULKAN_FUNCTION(CreateDescriptorSetLayout, VkResult, Device, const VkDescriptorSetLayoutCreateInfo*, const VkAllocationCallbacks*, VkDescriptorSetLayout*)
VULKAN_FUNCTION(DestroyDescriptorSetLayout, void, Device, VkDescriptorSetLayout, const VkAllocationCallbacks*)
VULKAN_FUNCTION(CreateDescriptorPool, VkResult, Device, const VkDescriptorPoolCreateInfo*, const VkAllocationCallbacks*, VkDescriptorPool*)
VULKAN_FUNCTION(DestroyDescriptorPool, void, Device, VkDescriptorPool, const VkAllocationCallbacks*)
VULKAN_FUNCTION(ResetDescriptorPool, VkResult, Device, VkDescriptorPool, VkDescriptorPoolResetFlags)
VULKAN_FUNCTION(AllocateDescriptorSets, VkResult, Device, const VkDescriptorSetAllocateInfo*, VkDescriptorSet*)
VULKAN_FUNCTION(FreeDescriptorSets, VkResult, Device, VkDescriptorPool, uint32_t, const VkDescriptorSet*)
VULKAN_FUNCTION(UpdateDescriptorSets, void, Device, uint32_t, const VkWriteDescriptorSet*, uint32_t, const VkCopyDescriptorSet*)
VULKAN_FUNCTION(CreateFramebuffer, VkResult, Device, const VkFramebufferCreateInfo*, const VkAllocationCallbacks*, VkFramebuffer*)
VULKAN_FUNCTION(DestroyFramebuffer, void, Device, VkFramebuffer, const VkAllocationCallbacks*)
VULKAN_FUNCTION(CreateRenderPass, VkResult, Device, const VkRenderPassCreateInfo*, const VkAllocationCallbacks*, VkRenderPass*)
VULKAN_FUNCTION(DestroyRenderPass, void, Device, VkRenderPass, const VkAllocationCallbacks*)
VULKAN_FUNCTION(GetRenderAreaGranularity, void, Device, VkRenderPass, VkExtent2D*)
VULKAN_FUNCTION(CreateCommandPool, VkResult, Device, const VkCommandPoolCreateInfo*, const VkAllocationCallbacks*, VkCommandPool*)
VULKAN_FUNCTION(DestroyCommandPool, void, Device, VkCommandPool, const VkAllocationCallbacks*)
VULKAN_FUNCTION(ResetCommandPool, VkResult, Device, VkCommandPool, VkCommandPoolResetFlags)
VULKAN_FUNCTION(AllocateCommandBuffers, VkResult, Device, const VkCommandBufferAllocateInfo*, VkCommandBuffer*)
VULKAN_FUNCTION(FreeCommandBuffers, void, Device, VkCommandPool, uint32_t, const VkCommandBuffer*)
VULKAN_FUNCTION(Begin, VkResult, CommandBuffer, const VkCommandBufferBeginInfo*)
VULKAN_FUNCTION(End, VkResult, CommandBuffer)
VULKAN_FUNCTION(Reset, VkResult, CommandBuffer, VkCommandBufferResetFlags)
VULKAN_FUNCTION(BindPipeline, void, CommandBuffer, VkPipelineBindPoint, VkPipeline)
VULKAN_FUNCTION(SetViewport, void, CommandBuffer, uint32_t, uint32_t, const VkViewport*)
VULKAN_FUNCTION(SetScissor, void, CommandBuffer, uint32_t, uint32_t, const VkRect2D*)
VULKAN_FUNCTION(SetLineWidth, void, CommandBuffer, float)
VULKAN_FUNCTION(SetDepthBias, void, CommandBuffer, float, float, float)
VULKAN_FUNCTION(SetBlendConstants, void, CommandBuffer, const float*)
VULKAN_FUNCTION(SetDepthBounds, void, CommandBuffer, float, float)
VULKAN_FUNCTION(SetStencilCompareMask, void, CommandBuffer, VkStencilFaceFlags, uint32_t)
VULKAN_FUNCTION(SetStencilWriteMask, void, CommandBuffer, VkStencilFaceFlags, uint32_t)
VULKAN_FUNCTION(SetStencilReference, void, CommandBuffer, VkStencilFaceFlags, uint32_t)
VULKAN_FUNCTION(BindDescriptorSets, void, CommandBuffer, VkPipelineBindPoint, VkPipelineLayout, uint32_t, uint32_t, const VkDescriptorSet*, uint32_t, const uint32_t*)
VULKAN_FUNCTION(BindIndexBuffer, void, CommandBuffer, VkBuffer, VkDeviceSize, VkIndexType)
VULKAN_FUNCTION(BindVertexBuffers, void, CommandBuffer, uint32_t, uint32_t, const VkBuffer*, const VkDeviceSize*)
VULKAN_FUNCTION(Draw, void, CommandBuffer, uint32_t, uint32_t, uint32_t, uint32_t)
VULKAN_FUNCTION(DrawIndexed, void, CommandBuffer, uint32_t, uint32_t, uint32_t, int32_t, uint32_t)
VULKAN_FUNCTION(DrawIndirect, void, CommandBuffer, VkBuffer, VkDeviceSize, uint32_t, uint32_t)
VULKAN_FUNCTION(DrawIndexedIndirect, void, CommandBuffer, VkBuffer, VkDeviceSize, uint32_t, uint32_t)
VULKAN_FUNCTION(Dispatch, void, CommandBuffer, uint32_t, uint32_t, uint32_t)
VULKAN_FUNCTION(DispatchIndirect, void, CommandBuffer, VkBuffer, VkDeviceSize)
VULKAN_FUNCTION(CopyBuffer, void, CommandBuffer, VkBuffer, VkBuffer, uint32_t, const VkBufferCopy*)
VULKAN_FUNCTION(CopyImage, void, CommandBuffer, VkImage, VkImageLayout, VkImage, VkImageLayout, uint32_t, const VkImageCopy*)
VULKAN_FUNCTION(BlitImage, void, CommandBuffer, VkImage, VkImageLayout, VkImage, VkImageLayout, uint32_t, const VkImageBlit*, VkFilter)
VULKAN_FUNCTION(CopyBufferToImage, void, CommandBuffer, VkBuffer, VkImage, VkImageLayout, uint32_t, const VkBufferImageCopy*)
VULKAN_FUNCTION(CopyImageToBuffer, void, CommandBuffer, VkImage, VkImageLayout, VkBuffer, uint32_t, const VkBufferImageCopy*)
VULKAN_FUNCTION(UpdateBuffer, void, CommandBuffer, VkBuffer, VkDeviceSize, VkDeviceSize, const void*)
VULKAN_FUNCTION(FillBuffer, void, CommandBuffer, VkBuffer, VkDeviceSize, VkDeviceSize, uint32_t)
VULKAN_FUNCTION(ClearColorImage, void, CommandBuffer, VkImage, VkImageLayout, const VkClearColorValue*, uint32_t, const VkImageSubresourceRange*)
VULKAN_FUNCTION(ClearDepthStencilImage, void, CommandBuffer, VkImage, VkImageLayout, const VkClearDepthStencilValue*, uint32_t, const VkImageSubresourceRange*)
VULKAN_FUNCTION(ClearAttachments, void, CommandBuffer, uint32_t, const VkClearAttachment*, uint32_t, const VkClearRect*)
VULKAN_FUNCTION(ResolveImage, void, CommandBuffer, VkImage, VkImageLayout, VkImage, VkImageLayout, uint32_t, const VkImageResolve*)
VULKAN_FUNCTION(SetEvent, void, CommandBuffer, VkEvent, VkPipelineStageFlags)
VULKAN_FUNCTION(ResetEvent, void, CommandBuffer, VkEvent, VkPipelineStageFlags)
VULKAN_FUNCTION(WaitEvents, void, CommandBuffer, uint32_t, const VkEvent*, VkPipelineStageFlags, VkPipelineStageFlags, uint32_t, const VkMemoryBarrier*, uint32_t, const VkBufferMemoryBarrier*, uint32_t, const VkImageMemoryBarrier*)
VULKAN_FUNCTION(PipelineBarrier, void, CommandBuffer, VkPipelineStageFlags, VkPipelineStageFlags, VkDependencyFlags, uint32_t, const VkMemoryBarrier*, uint32_t, const VkBufferMemoryBarrier*, uint32_t, const VkImageMemoryBarrier*)
VULKAN_FUNCTION(BeginQuery, void, CommandBuffer, VkQueryPool, uint32_t, VkQueryControlFlags)
VULKAN_FUNCTION(EndQuery, void, CommandBuffer, VkQueryPool, uint32_t)
VULKAN_FUNCTION(ResetQueryPool, void, CommandBuffer, VkQueryPool, uint32_t, uint32_t)
VULKAN_FUNCTION(WriteTimestamp, void, CommandBuffer, VkPipelineStageFlagBits, VkQueryPool, uint32_t)
VULKAN_FUNCTION(CopyQueryPoolResults, void, CommandBuffer, VkQueryPool, uint32_t, uint32_t, VkBuffer, VkDeviceSize, VkDeviceSize, VkQueryResultFlags)
VULKAN_FUNCTION(PushConstants, void, CommandBuffer, VkPipelineLayout, VkShaderStageFlags, uint32_t, uint32_t, const void*)
VULKAN_FUNCTION(BeginRenderPass, void, CommandBuffer, const VkRenderPassBeginInfo*, VkSubpassContents)
VULKAN_FUNCTION(NextSubpass, void, CommandBuffer, VkSubpassContents)
VULKAN_FUNCTION(EndRenderPass, void, CommandBuffer)
VULKAN_FUNCTION(ExecuteCommands, void, CommandBuffer, uint32_t, const VkCommandBuffer*)
VULKAN_FUNCTION(BindBufferMemory2, VkResult, Device, uint32_t, const VkBindBufferMemoryInfo*)
VULKAN_FUNCTION(BindImageMemory2, VkResult, Device, uint32_t, const VkBindImageMemoryInfo*)
VULKAN_FUNCTION(GetDeviceGroupPeerMemoryFeatures, void, Device, uint32_t, uint32_t, uint32_t, VkPeerMemoryFeatureFlags*)
VULKAN_FUNCTION(SetDeviceMask, void, CommandBuffer, uint32_t)
VULKAN_FUNCTION(DispatchBase, void, CommandBuffer, uint32_t, uint32_t, uint32_t, uint32_t, uint32_t, uint32_t)
VULKAN_FUNCTION(EnumeratePhysicalDeviceGroups, VkResult, Instance, uint32_t*, VkPhysicalDeviceGroupProperties*)
VULKAN_FUNCTION(GetImageMemoryRequirements2, void, Device, const VkImageMemoryRequirementsInfo2*, VkMemoryRequirements2*)
VULKAN_FUNCTION(GetBufferMemoryRequirements2, void, Device, const VkBufferMemoryRequirementsInfo2*, VkMemoryRequirements2*)
VULKAN_FUNCTION(GetImageSparseMemoryRequirements2, void, Device, const VkImageSparseMemoryRequirementsInfo2*, uint32_t*, VkSparseImageMemoryRequirements2*)
VULKAN_FUNCTION(GetSparseImageFormatProperties2, void, PhysicalDevice, const VkPhysicalDeviceSparseImageFormatInfo2*, uint32_t*, VkSparseImageFormatProperties2*)
VULKAN_FUNCTION(TrimCommandPool, void, Device, VkCommandPool, VkCommandPoolTrimFlags)
VULKAN_FUNCTION(GetDeviceQueue2, void, Device, const VkDeviceQueueInfo2*, VkQueue*)
VULKAN_FUNCTION(CreateSamplerYcbcrConversion, VkResult, Device, const VkSamplerYcbcrConversionCreateInfo*, const VkAllocationCallbacks*, VkSamplerYcbcrConversion*)
VULKAN_FUNCTION(DestroySamplerYcbcrConversion, void, Device, VkSamplerYcbcrConversion, const VkAllocationCallbacks*)
VULKAN_FUNCTION(CreateDescriptorUpdateTemplate, VkResult, Device, const VkDescriptorUpdateTemplateCreateInfo*, const VkAllocationCallbacks*, VkDescriptorUpdateTemplate*)
VULKAN_FUNCTION(DestroyDescriptorUpdateTemplate, void, Device, VkDescriptorUpdateTemplate, const VkAllocationCallbacks*)
VULKAN_FUNCTION(UpdateDescriptorSetWithTemplate, void, Device, VkDescriptorSet, VkDescriptorUpdateTemplate, const void*)
VULKAN_FUNCTION(GetExternalBufferProperties, void, PhysicalDevice, const VkPhysicalDeviceExternalBufferInfo*, VkExternalBufferProperties*)
VULKAN_FUNCTION(GetExternalFenceProperties, void, PhysicalDevice, const VkPhysicalDeviceExternalFenceInfo*, VkExternalFenceProperties*)
VULKAN_FUNCTION(GetExternalSemaphoreProperties, void, PhysicalDevice, const VkPhysicalDeviceExternalSemaphoreInfo*, VkExternalSemaphoreProperties*)
VULKAN_FUNCTION(GetDescriptorSetLayoutSupport, void, Device, const VkDescriptorSetLayoutCreateInfo*, VkDescriptorSetLayoutSupport*)
VULKAN_FUNCTION(DestroySurface, void, Instance, VkSurfaceKHR, const VkAllocationCallbacks*)
VULKAN_FUNCTION(GetSurfaceSupport, VkResult, PhysicalDevice, uint32_t, VkSurfaceKHR, VkBool32*)
VULKAN_FUNCTION(GetSurfaceCapabilities, VkResult, PhysicalDevice, VkSurfaceKHR, VkSurfaceCapabilitiesKHR*)
VULKAN_FUNCTION(GetSurfaceFormats, VkResult, PhysicalDevice, VkSurfaceKHR, uint32_t*, VkSurfaceFormatKHR*)
VULKAN_FUNCTION(GetSurfacePresentModes, VkResult, PhysicalDevice, VkSurfaceKHR, uint32_t*, VkPresentModeKHR*)
VULKAN_FUNCTION(CreateSwapchain, VkResult, Device, const VkSwapchainCreateInfoKHR*, const VkAllocationCallbacks*, VkSwapchainKHR*)
VULKAN_FUNCTION(DestroySwapchain, void, Device, VkSwapchainKHR, const VkAllocationCallbacks*)
VULKAN_FUNCTION(GetSwapchainImages, VkResult, Device, VkSwapchainKHR, uint32_t*, VkImage*)
VULKAN_FUNCTION(AcquireNextImage, VkResult, Device, VkSwapchainKHR, uint64_t, VkSemaphore, VkFence, uint32_t*)
VULKAN_FUNCTION(Present, VkResult, Queue, const VkPresentInfoKHR*)
VULKAN_FUNCTION(GetDeviceGroupPresentCapabilities, VkResult, Device, VkDeviceGroupPresentCapabilitiesKHR*)
VULKAN_FUNCTION(GetDeviceGroupSurfacePresentModes, VkResult, Device, VkSurfaceKHR, VkDeviceGroupPresentModeFlagsKHR*)
VULKAN_FUNCTION(GetPresentRectangles, VkResult, PhysicalDevice, VkSurfaceKHR, uint32_t*, VkRect2D*)
VULKAN_FUNCTION(AcquireNextImage2, VkResult, Device, const VkAcquireNextImageInfoKHR*, uint32_t*)
VULKAN_FUNCTION(GetDisplayProperties, VkResult, PhysicalDevice, uint32_t*, VkDisplayPropertiesKHR*)
VULKAN_FUNCTION(GetDisplayPlaneProperties, VkResult, PhysicalDevice, uint32_t*, VkDisplayPlanePropertiesKHR*)
VULKAN_FUNCTION(GetDisplayPlaneSupportedDisplays, VkResult, PhysicalDevice, uint32_t, uint32_t*, VkDisplayKHR*)
VULKAN_FUNCTION(GetDisplayModeProperties, VkResult, PhysicalDevice, VkDisplayKHR, uint32_t*, VkDisplayModePropertiesKHR*)
VULKAN_FUNCTION(CreateDisplayMode, VkResult, PhysicalDevice, VkDisplayKHR, const VkDisplayModeCreateInfoKHR*, const VkAllocationCallbacks*, VkDisplayModeKHR*)
VULKAN_FUNCTION(GetDisplayPlaneCapabilities, VkResult, PhysicalDevice, VkDisplayModeKHR, uint32_t, VkDisplayPlaneCapabilitiesKHR*)
VULKAN_FUNCTION(CreateDisplayPlaneSurface, VkResult, Instance, const VkDisplaySurfaceCreateInfoKHR*, const VkAllocationCallbacks*, VkSurfaceKHR*)
VULKAN_FUNCTION(CreateSharedSwapchains, VkResult, Device, uint32_t, const VkSwapchainCreateInfoKHR*, const VkAllocationCallbacks*, VkSwapchainKHR*)
VULKAN_FUNCTION(GetFeatures2, void, PhysicalDevice, VkPhysicalDeviceFeatures2*)
VULKAN_FUNCTION(GetProperties2, void, PhysicalDevice, VkPhysicalDeviceProperties2*)
VULKAN_FUNCTION(GetFormatProperties2, void, PhysicalDevice, VkFormat, VkFormatProperties2*)
VULKAN_FUNCTION(GetImageFormatProperties2, VkResult, PhysicalDevice, const VkPhysicalDeviceImageFormatInfo2*, VkImageFormatProperties2*)
VULKAN_FUNCTION(GetQueueFamilyProperties2, void, PhysicalDevice, uint32_t*, VkQueueFamilyProperties2*)
VULKAN_FUNCTION(GetMemoryProperties2, void, PhysicalDevice, VkPhysicalDeviceMemoryProperties2*)
VULKAN_FUNCTION(GetMemoryFd, VkResult, Device, const VkMemoryGetFdInfoKHR*, int*)
VULKAN_FUNCTION(GetMemoryFdProperties, VkResult, Device, VkExternalMemoryHandleTypeFlagBits, int, VkMemoryFdPropertiesKHR*)
VULKAN_FUNCTION(ImportSemaphoreFd, VkResult, Device, const VkImportSemaphoreFdInfoKHR*)
VULKAN_FUNCTION(GetSemaphoreFd, VkResult, Device, const VkSemaphoreGetFdInfoKHR*, int*)
VULKAN_FUNCTION(PushDescriptorSet, void, CommandBuffer, VkPipelineBindPoint, VkPipelineLayout, uint32_t, uint32_t, const VkWriteDescriptorSet*)
VULKAN_FUNCTION(PushDescriptorSetWithTemplate, void, CommandBuffer, VkDescriptorUpdateTemplate, VkPipelineLayout, uint32_t, const void*)
VULKAN_FUNCTION(CreateRenderPass2, VkResult, Device, const VkRenderPassCreateInfo2KHR*, const VkAllocationCallbacks*, VkRenderPass*)
VULKAN_FUNCTION(BeginRenderPass2, void, CommandBuffer, const VkRenderPassBeginInfo*, const VkSubpassBeginInfoKHR*)
VULKAN_FUNCTION(NextSubpass2, void, CommandBuffer, const VkSubpassBeginInfoKHR*, const VkSubpassEndInfoKHR*)
VULKAN_FUNCTION(EndRenderPass2, void, CommandBuffer, const VkSubpassEndInfoKHR*)
VULKAN_FUNCTION(GetSwapchainStatus, VkResult, Device, VkSwapchainKHR)
VULKAN_FUNCTION(ImportFenceFd, VkResult, Device, const VkImportFenceFdInfoKHR*)
VULKAN_FUNCTION(GetFenceFd, VkResult, Device, const VkFenceGetFdInfoKHR*, int*)
VULKAN_FUNCTION(GetSurfaceCapabilities2, VkResult, PhysicalDevice, const VkPhysicalDeviceSurfaceInfo2KHR*, VkSurfaceCapabilities2KHR*)
VULKAN_FUNCTION(GetSurfaceFormats2, VkResult, PhysicalDevice, const VkPhysicalDeviceSurfaceInfo2KHR*, uint32_t*, VkSurfaceFormat2KHR*)
VULKAN_FUNCTION(GetDisplayProperties2, VkResult, PhysicalDevice, uint32_t*, VkDisplayProperties2KHR*)
VULKAN_FUNCTION(GetDisplayPlaneProperties2, VkResult, PhysicalDevice, uint32_t*, VkDisplayPlaneProperties2KHR*)
VULKAN_FUNCTION(GetDisplayModeProperties2, VkResult, PhysicalDevice, VkDisplayKHR, uint32_t*, VkDisplayModeProperties2KHR*)
VULKAN_FUNCTION(GetDisplayPlaneCapabilities2, VkResult, PhysicalDevice, const VkDisplayPlaneInfo2KHR*, VkDisplayPlaneCapabilities2KHR*)
VULKAN_FUNCTION(DrawIndirectCount, void, CommandBuffer, VkBuffer, VkDeviceSize, VkBuffer, VkDeviceSize, uint32_t, uint32_t)
VULKAN_FUNCTION(DrawIndexedIndirectCount, void, CommandBuffer, VkBuffer, VkDeviceSize, VkBuffer, VkDeviceSize, uint32_t, uint32_t)
VULKAN_FUNCTION(GetPipelineExecutableProperties, VkResult, Device, const VkPipelineInfoKHR*, uint32_t*, VkPipelineExecutablePropertiesKHR*)
VULKAN_FUNCTION(GetPipelineExecutableStatistics, VkResult, Device, const VkPipelineExecutableInfoKHR*, uint32_t*, VkPipelineExecutableStatisticKHR*)
VULKAN_FUNCTION(GetPipelineExecutableInternalRepresentations, VkResult, Device, const VkPipelineExecutableInfoKHR*, uint32_t*, VkPipelineExecutableInternalRepresentationKHR*)
VULKAN_FUNCTION(CreateDebugReportCallback, VkResult, Instance, const VkDebugReportCallbackCreateInfoEXT*, const VkAllocationCallbacks*, VkDebugReportCallbackEXT*)
VULKAN_FUNCTION(DestroyDebugReportCallback, void, Instance, VkDebugReportCallbackEXT, const VkAllocationCallbacks*)
VULKAN_FUNCTION(DebugReportMessage, void, Instance, VkDebugReportFlagsEXT, VkDebugReportObjectTypeEXT, uint64_t, size_t, int32_t, const char*, const char*)
VULKAN_FUNCTION(DebugMarkerSetObjectTag, VkResult, Device, const VkDebugMarkerObjectTagInfoEXT*)
VULKAN_FUNCTION(DebugMarkerSetObjectName, VkResult, Device, const VkDebugMarkerObjectNameInfoEXT*)
VULKAN_FUNCTION(DebugMarkerBegin, void, CommandBuffer, const VkDebugMarkerMarkerInfoEXT*)
VULKAN_FUNCTION(DebugMarkerEnd, void, CommandBuffer)
VULKAN_FUNCTION(DebugMarkerInsert, void, CommandBuffer, const VkDebugMarkerMarkerInfoEXT*)
VULKAN_FUNCTION(BindTransformFeedbackBuffers, void, CommandBuffer, uint32_t, uint32_t, const VkBuffer*, const VkDeviceSize*, const VkDeviceSize*)
VULKAN_FUNCTION(BeginTransformFeedback, void, CommandBuffer, uint32_t, uint32_t, const VkBuffer*, const VkDeviceSize*)
VULKAN_FUNCTION(EndTransformFeedback, void, CommandBuffer, uint32_t, uint32_t, const VkBuffer*, const VkDeviceSize*)
VULKAN_FUNCTION(BeginQueryIndexed, void, CommandBuffer, VkQueryPool, uint32_t, VkQueryControlFlags, uint32_t)
VULKAN_FUNCTION(EndQueryIndexed, void, CommandBuffer, VkQueryPool, uint32_t, uint32_t)
VULKAN_FUNCTION(DrawIndirectByteCount, void, CommandBuffer, uint32_t, uint32_t, VkBuffer, VkDeviceSize, uint32_t, uint32_t)
VULKAN_FUNCTION(GetImageViewHandleNVX, uint32_t, Device, const VkImageViewHandleInfoNVX*)
VULKAN_FUNCTION(GetShaderInfoAMD, VkResult, Device, VkPipeline, VkShaderStageFlagBits, VkShaderInfoTypeAMD, size_t*, void*)
VULKAN_FUNCTION(GetExternalImageFormatPropertiesNV, VkResult, PhysicalDevice, VkFormat, VkImageType, VkImageTiling, VkImageUsageFlags, VkImageCreateFlags, VkExternalMemoryHandleTypeFlagsNV, VkExternalImageFormatPropertiesNV*)
VULKAN_FUNCTION(BeginConditionalRendering, void, CommandBuffer, const VkConditionalRenderingBeginInfoEXT*)
VULKAN_FUNCTION(EndConditionalRendering, void, CommandBuffer)
VULKAN_FUNCTION(ProcessCommands, void, CommandBuffer, const VkCmdProcessCommandsInfoNVX*)
VULKAN_FUNCTION(ReserveSpaceForCommands, void, CommandBuffer, const VkCmdReserveSpaceForCommandsInfoNVX*)
VULKAN_FUNCTION(CreateIndirectCommandsLayoutNVX, VkResult, Device, const VkIndirectCommandsLayoutCreateInfoNVX*, const VkAllocationCallbacks*, VkIndirectCommandsLayoutNVX*)
VULKAN_FUNCTION(DestroyIndirectCommandsLayoutNVX, void, Device, VkIndirectCommandsLayoutNVX, const VkAllocationCallbacks*)
VULKAN_FUNCTION(CreateObjectTableNVX, VkResult, Device, const VkObjectTableCreateInfoNVX*, const VkAllocationCallbacks*, VkObjectTableNVX*)
VULKAN_FUNCTION(DestroyObjectTableNVX, void, Device, VkObjectTableNVX, const VkAllocationCallbacks*)
VULKAN_FUNCTION(RegisterObjectsNVX, VkResult, Device, VkObjectTableNVX, uint32_t, const VkObjectTableEntryNVX* const*, const uint32_t*)
VULKAN_FUNCTION(UnregisterObjectsNVX, VkResult, Device, VkObjectTableNVX, uint32_t, const VkObjectEntryTypeNVX*, const uint32_t*)
VULKAN_FUNCTION(GetGeneratedCommandsPropertiesNVX, void, PhysicalDevice, VkDeviceGeneratedCommandsFeaturesNVX*, VkDeviceGeneratedCommandsLimitsNVX*)
VULKAN_FUNCTION(SetViewportWScaling, void, CommandBuffer, uint32_t, uint32_t, const VkViewportWScalingNV*)
VULKAN_FUNCTION(ReleaseDisplay, VkResult, PhysicalDevice, VkDisplayKHR)
VULKAN_FUNCTION(GetSurfaceCapabilities2KHR, VkResult, PhysicalDevice, const VkPhysicalDeviceSurfaceInfo2KHR*, VkSurfaceCapabilities2KHR*)
VULKAN_FUNCTION(DisplayPowerControl, VkResult, Device, VkDisplayKHR, const VkDisplayPowerInfoEXT*)
VULKAN_FUNCTION(RegisterDeviceEvent, VkResult, Device, const VkDeviceEventInfoEXT*, const VkAllocationCallbacks*, VkFence*)
VULKAN_FUNCTION(RegisterDisplayEvent, VkResult, Device, VkDisplayKHR, const VkDisplayEventInfoEXT*, const VkAllocationCallbacks*, VkFence*)
VULKAN_FUNCTION(GetSwapchainCounter, VkResult, Device, VkSwapchainKHR, VkSurfaceCounterFlagBitsEXT, uint64_t*)
VULKAN_FUNCTION(GetRefreshCycleDurationGOOGLE, VkResult, Device, VkSwapchainKHR, VkRefreshCycleDurationGOOGLE*)
VULKAN_FUNCTION(GetPastPresentationTimingGOOGLE, VkResult, Device, VkSwapchainKHR, uint32_t*, VkPastPresentationTimingGOOGLE*)
VULKAN_FUNCTION(SetDiscardRectangle, void, CommandBuffer, uint32_t, uint32_t, const VkRect2D*)
VULKAN_FUNCTION(SetHdrMetadata, void, Device, uint32_t, const VkSwapchainKHR*, const VkHdrMetadataEXT*)
VULKAN_FUNCTION(SetDebugUtilsObjectName, VkResult, Device, const VkDebugUtilsObjectNameInfoEXT*)
VULKAN_FUNCTION(SetDebugUtilsObjectTag, VkResult, Device, const VkDebugUtilsObjectTagInfoEXT*)
VULKAN_FUNCTION(BeginDebugUtilsLabel, void, Queue, const VkDebugUtilsLabelEXT*)
VULKAN_FUNCTION(EndDebugUtilsLabel, void, Queue)
VULKAN_FUNCTION(InsertDebugUtilsLabel, void, Queue, const VkDebugUtilsLabelEXT*)
VULKAN_FUNCTION(BeginDebugUtilsLabel, void, CommandBuffer, const VkDebugUtilsLabelEXT*)
VULKAN_FUNCTION(EndDebugUtilsLabel, void, CommandBuffer)
VULKAN_FUNCTION(InsertDebugUtilsLabel, void, CommandBuffer, const VkDebugUtilsLabelEXT*)
VULKAN_FUNCTION(CreateDebugUtilsMessenger, VkResult, Instance, const VkDebugUtilsMessengerCreateInfoEXT*, const VkAllocationCallbacks*, VkDebugUtilsMessengerEXT*)
VULKAN_FUNCTION(DestroyDebugUtilsMessenger, void, Instance, VkDebugUtilsMessengerEXT, const VkAllocationCallbacks*)
VULKAN_FUNCTION(SubmitDebugUtilsMessage, void, Instance, VkDebugUtilsMessageSeverityFlagBitsEXT, VkDebugUtilsMessageTypeFlagsEXT, const VkDebugUtilsMessengerCallbackDataEXT*)
VULKAN_FUNCTION(SetSampleLocations, void, CommandBuffer, const VkSampleLocationsInfoEXT*)
VULKAN_FUNCTION(GetMultisampleProperties, void, PhysicalDevice, VkSampleCountFlagBits, VkMultisamplePropertiesEXT*)
VULKAN_FUNCTION(GetImageDrmFormatModifierProperties, VkResult, Device, VkImage, VkImageDrmFormatModifierPropertiesEXT*)
VULKAN_FUNCTION(CreateValidationCache, VkResult, Device, const VkValidationCacheCreateInfoEXT*, const VkAllocationCallbacks*, VkValidationCacheEXT*)
VULKAN_FUNCTION(DestroyValidationCache, void, Device, VkValidationCacheEXT, const VkAllocationCallbacks*)
VULKAN_FUNCTION(MergeValidationCaches, VkResult, Device, VkValidationCacheEXT, uint32_t, const VkValidationCacheEXT*)
VULKAN_FUNCTION(GetValidationCacheData, VkResult, Device, VkValidationCacheEXT, size_t*, void*)
VULKAN_FUNCTION(BindShadingRateImage, void, CommandBuffer, VkImageView, VkImageLayout)
VULKAN_FUNCTION(SetViewportShadingRatePalette, void, CommandBuffer, uint32_t, uint32_t, const VkShadingRatePaletteNV*)
VULKAN_FUNCTION(SetCoarseSampleOrder, void, CommandBuffer, VkCoarseSampleOrderTypeNV, uint32_t, const VkCoarseSampleOrderCustomNV*)
VULKAN_FUNCTION(CreateAccelerationStructureNV, VkResult, Device, const VkAccelerationStructureCreateInfoNV*, const VkAllocationCallbacks*, VkAccelerationStructureNV*)
VULKAN_FUNCTION(DestroyAccelerationStructureNV, void, Device, VkAccelerationStructureNV, const VkAllocationCallbacks*)
VULKAN_FUNCTION(GetAccelerationStructureMemoryRequirementsNV, void, Device, const VkAccelerationStructureMemoryRequirementsInfoNV*, VkMemoryRequirements2KHR*)
VULKAN_FUNCTION(BindAccelerationStructureMemoryNV, VkResult, Device, uint32_t, const VkBindAccelerationStructureMemoryInfoNV*)
VULKAN_FUNCTION(BuildAccelerationStructure, void, CommandBuffer, const VkAccelerationStructureInfoNV*, VkBuffer, VkDeviceSize, VkBool32, VkAccelerationStructureNV, VkAccelerationStructureNV, VkBuffer, VkDeviceSize)
VULKAN_FUNCTION(CopyAccelerationStructure, void, CommandBuffer, VkAccelerationStructureNV, VkAccelerationStructureNV, VkCopyAccelerationStructureModeNV)
VULKAN_FUNCTION(TraceRays, void, CommandBuffer, VkBuffer, VkDeviceSize, VkBuffer, VkDeviceSize, VkDeviceSize, VkBuffer, VkDeviceSize, VkDeviceSize, VkBuffer, VkDeviceSize, VkDeviceSize, uint32_t, uint32_t, uint32_t)
VULKAN_FUNCTION(CreateRayTracingPipelinesNV, VkResult, Device, VkPipelineCache, uint32_t, const VkRayTracingPipelineCreateInfoNV*, const VkAllocationCallbacks*, VkPipeline*)
VULKAN_FUNCTION(GetRayTracingShaderGroupHandlesNV, VkResult, Device, VkPipeline, uint32_t, uint32_t, size_t, void*)
VULKAN_FUNCTION(GetAccelerationStructureHandleNV, VkResult, Device, VkAccelerationStructureNV, size_t, void*)
VULKAN_FUNCTION(WriteAccelerationStructuresProperties, void, CommandBuffer, uint32_t, const VkAccelerationStructureNV*, VkQueryType, VkQueryPool, uint32_t)
VULKAN_FUNCTION(CompileDeferredNV, VkResult, Device, VkPipeline, uint32_t)
VULKAN_FUNCTION(GetMemoryHostPointerProperties, VkResult, Device, VkExternalMemoryHandleTypeFlagBits, const void*, VkMemoryHostPointerPropertiesEXT*)
VULKAN_FUNCTION(WriteBufferMarker, void, CommandBuffer, VkPipelineStageFlagBits, VkBuffer, VkDeviceSize, uint32_t)
VULKAN_FUNCTION(GetCalibrateableTimeDomains, VkResult, PhysicalDevice, uint32_t*, VkTimeDomainEXT*)
VULKAN_FUNCTION(GetCalibratedTimestamps, VkResult, Device, uint32_t, const VkCalibratedTimestampInfoEXT*, uint64_t*, uint64_t*)
VULKAN_FUNCTION(DrawMeshTasks, void, CommandBuffer, uint32_t, uint32_t)
VULKAN_FUNCTION(DrawMeshTasksIndirect, void, CommandBuffer, VkBuffer, VkDeviceSize, uint32_t, uint32_t)
VULKAN_FUNCTION(DrawMeshTasksIndirectCount, void, CommandBuffer, VkBuffer, VkDeviceSize, VkBuffer, VkDeviceSize, uint32_t, uint32_t)
VULKAN_FUNCTION(SetExclusiveScissor, void, CommandBuffer, uint32_t, uint32_t, const VkRect2D*)
VULKAN_FUNCTION(SetCheckpoint, void, CommandBuffer, const void*)
VULKAN_FUNCTION(GetCheckpointData, void, Queue, uint32_t*, VkCheckpointDataNV*)
VULKAN_FUNCTION(InitializePerformanceApiINTEL, VkResult, Device, const VkInitializePerformanceApiInfoINTEL*)
VULKAN_FUNCTION(UninitializePerformanceApiINTEL, void, Device)
VULKAN_FUNCTION(SetPerformanceMarker, VkResult, CommandBuffer, const VkPerformanceMarkerInfoINTEL*)
VULKAN_FUNCTION(SetPerformanceStreamMarker, VkResult, CommandBuffer, const VkPerformanceStreamMarkerInfoINTEL*)
VULKAN_FUNCTION(SetPerformanceOverride, VkResult, CommandBuffer, const VkPerformanceOverrideInfoINTEL*)
VULKAN_FUNCTION(AcquirePerformanceConfigurationINTEL, VkResult, Device, const VkPerformanceConfigurationAcquireInfoINTEL*, VkPerformanceConfigurationINTEL*)
VULKAN_FUNCTION(ReleasePerformanceConfigurationINTEL, VkResult, Device, VkPerformanceConfigurationINTEL)
VULKAN_FUNCTION(SetPerformanceConfiguration, VkResult, Queue, VkPerformanceConfigurationINTEL)
VULKAN_FUNCTION(GetPerformanceParameterINTEL, VkResult, Device, VkPerformanceParameterTypeINTEL, VkPerformanceValueINTEL*)
VULKAN_FUNCTION(SetLocalDimmingAMD, void, Device, VkSwapchainKHR, VkBool32)
VULKAN_FUNCTION(GetBufferDeviceAddress, VkDeviceAddress, Device, const VkBufferDeviceAddressInfoEXT*)
VULKAN_FUNCTION(GetCooperativeMatrixPropertiesNV, VkResult, PhysicalDevice, uint32_t*, VkCooperativeMatrixPropertiesNV*)
VULKAN_FUNCTION(GetSupportedFramebufferMixedSamplesCombinationsNV, VkResult, PhysicalDevice, uint32_t*, VkFramebufferMixedSamplesCombinationNV*)
VULKAN_FUNCTION(CreateHeadlessSurface, VkResult, Instance, const VkHeadlessSurfaceCreateInfoEXT*, const VkAllocationCallbacks*, VkSurfaceKHR*)
VULKAN_FUNCTION(SetLineStipple, void, CommandBuffer, uint32_t, uint16_t)
VULKAN_FUNCTION(ResetQueryPool, void, Device, VkQueryPool, uint32_t, uint32_t)
#if defined(VK_USE_PLATFORM_WIN32_KHR)
VULKAN_FUNCTION(CreateWin32Surface, VkResult, Instance, const VkWin32SurfaceCreateInfoKHR*, const VkAllocationCallbacks*, VkSurfaceKHR*)
VULKAN_FUNCTION(GetWin32PresentationSupport, VkBool32, PhysicalDevice, uint32_t)
VULKAN_FUNCTION(GetMemoryWin32Handle, VkResult, Device, const VkMemoryGetWin32HandleInfoKHR*, HANDLE*)
VULKAN_FUNCTION(GetMemoryWin32HandleProperties, VkResult, Device, VkExternalMemoryHandleTypeFlagBits, HANDLE, VkMemoryWin32HandlePropertiesKHR*)
VULKAN_FUNCTION(ImportSemaphoreWin32Handle, VkResult, Device, const VkImportSemaphoreWin32HandleInfoKHR*)
VULKAN_FUNCTION(GetSemaphoreWin32Handle, VkResult, Device, const VkSemaphoreGetWin32HandleInfoKHR*, HANDLE*)
VULKAN_FUNCTION(ImportFenceWin32Handle, VkResult, Device, const VkImportFenceWin32HandleInfoKHR*)
VULKAN_FUNCTION(GetFenceWin32Handle, VkResult, Device, const VkFenceGetWin32HandleInfoKHR*, HANDLE*)
VULKAN_FUNCTION(GetMemoryWin32HandleNV, VkResult, Device, VkDeviceMemory, VkExternalMemoryHandleTypeFlagsNV, HANDLE*)
VULKAN_FUNCTION(GetSurfacePresentModes2, VkResult, PhysicalDevice, const VkPhysicalDeviceSurfaceInfo2KHR*, uint32_t*, VkPresentModeKHR*)
VULKAN_FUNCTION(AcquireFullScreenExclusiveMode, VkResult, Device, VkSwapchainKHR)
VULKAN_FUNCTION(ReleaseFullScreenExclusiveMode, VkResult, Device, VkSwapchainKHR)
VULKAN_FUNCTION(GetDeviceGroupSurfacePresentModes2, VkResult, Device, const VkPhysicalDeviceSurfaceInfo2KHR*, VkDeviceGroupPresentModeFlagsKHR*)
#endif
#if defined(VK_USE_PLATFORM_XCB_KHR)
VULKAN_FUNCTION(CreateXcbSurface, VkResult, Instance, const VkXcbSurfaceCreateInfoKHR*, const VkAllocationCallbacks*, VkSurfaceKHR*)
VULKAN_FUNCTION(GetPhysicalDeviceXcbPresentationSupport, VkBool32, PhysicalDevice, uint32_t, xcb_connection_t*, xcb_visualid_t)
#endif
#if defined(VK_USE_PLATFORM_XLIB_KHR)
VULKAN_FUNCTION(CreateXlibSurface, VkResult, Instance, const VkXlibSurfaceCreateInfoKHR*, const VkAllocationCallbacks*, VkSurfaceKHR*)
VULKAN_FUNCTION(GetPhysicalDeviceXlibPresentationSupport, VkBool32, PhysicalDevice, uint32_t, Display*, VisualID)
#endif
#if defined(VK_USE_PLATFORM_XLIB_XRANDR_EXT)
VULKAN_FUNCTION(AcquireXlibDisplay, VkResult, PhysicalDevice, Display * dpy, VkDisplayKHR)
VULKAN_FUNCTION(GetRandROutputDisplay, VkResult, PhysicalDevice, Display*, RROutput, VkDisplayKHR*)
#endif
