name: C/C++ CI

on:
  push:
    branches: 
      - master

jobs:
  build:
    name: Build on Ubuntu
    runs-on: [ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v1
    - name: get dependancies
      run: |
        sudo apt -y install libglm-dev glslang-dev llvm-8-dev
    - name: make
      run: |
        mkdir build
        cd build
        cmake ..
        make
